-- Enable vector extension for RAG knowledge base embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Health Profiles (Routers profile.py)
CREATE TABLE IF NOT EXISTS health_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    age INT,
    blood_type TEXT,
    conditions TEXT[],
    medications TEXT[],
    allergies TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. User Profiles (Agent tools.py)
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT,
    full_name TEXT,
    age INT,
    gender TEXT,
    height_cm NUMERIC,
    weight_kg NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Conversations (Chat history)
CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    title TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Messages (Chat history)
CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Medical Documents (RAG Knowledge Base & vector search)
CREATE TABLE IF NOT EXISTS medical_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    source TEXT,
    embedding VECTOR(384),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Vector match function for medical_documents
CREATE OR REPLACE FUNCTION match_medical_documents (
    query_embedding VECTOR(384),
    match_count INT DEFAULT 5
)
RETURNS TABLE (
    id BIGINT,
    content TEXT,
    source TEXT,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        medical_documents.id,
        medical_documents.content,
        medical_documents.source,
        1 - (medical_documents.embedding <=> query_embedding) AS similarity
    FROM medical_documents
    ORDER BY medical_documents.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- 6. Ring Data (Health router overview)
CREATE TABLE IF NOT EXISTS ring_data (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    recorded_at TIMESTAMPTZ DEFAULT NOW(),
    sleep_duration_minutes INT,
    heart_rate_avg INT,
    steps INT,
    spo2_avg NUMERIC,
    sleep_score INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. User Sleep
CREATE TABLE IF NOT EXISTS user_sleep (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    date DATE NOT NULL,
    total_duration INT,
    sleep_score INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. User Daily HR
CREATE TABLE IF NOT EXISTS user_hr (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    date DATE NOT NULL,
    avg_hr NUMERIC,
    min_hr NUMERIC,
    max_hr NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. User HR Readings (Live/instant readings)
CREATE TABLE IF NOT EXISTS user_hr_readings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    measured_at TIMESTAMPTZ DEFAULT NOW(),
    value_bpm INT,
    source TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. User SpO2
CREATE TABLE IF NOT EXISTS user_spo2 (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    date DATE NOT NULL,
    avg_spo2 NUMERIC,
    min_spo2 NUMERIC,
    max_spo2 NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. User HRV
CREATE TABLE IF NOT EXISTS user_hrv (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    date DATE NOT NULL,
    avg_hrv NUMERIC,
    min_hrv NUMERIC,
    max_hrv NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. User Blood Pressure
CREATE TABLE IF NOT EXISTS user_bp (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    measured_at TIMESTAMPTZ DEFAULT NOW(),
    systolic INT,
    diastolic INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. User Steps
CREATE TABLE IF NOT EXISTS user_steps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    date DATE NOT NULL,
    steps INT,
    calories INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. User Temperature
CREATE TABLE IF NOT EXISTS user_temp (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    measured_at TIMESTAMPTZ DEFAULT NOW(),
    value_c NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. User Stress
CREATE TABLE IF NOT EXISTS user_stress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    measured_at TIMESTAMPTZ DEFAULT NOW(),
    stress_value INT,
    label TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. User Menstrual Cycles
CREATE TABLE IF NOT EXISTS user_cycles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    period_start DATE,
    period_end DATE,
    cycle_length INT DEFAULT 28,
    period_length INT DEFAULT 5,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
